### ISSUE TITLE
get metadata crashes

### ISSUE THREAD

**Issue by LucaCoduriV** [jld3103/dart-mpris#3]
I'm attempting to retrieve metadata for all players. However, I've encountered instances where a player doesn't possess any metadata, rendering the plugin ineffective. Is there a method to verify its existence?

Here is the error message:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a
 subtype of type 'DBusUint32' in type cast
#0      new Metadata.fromMap (package:mpris/mpris.dart:238:41)
#1      MPRISPlayer.getMetadata (package:mpris/mpris.dart:130:16)
<asynchronous suspension>
```
https://github.com/provokateurin/dart-mpris/blob/503ac624de04bea1713cef3f586ce70c6679eec8/lib/mpris.dart#L230-L253

I'll try to fix it by myself and will make a pull request.

**Comment by LucaCoduriV** [comment]
Upon reviewing various forks of your repository, I came across the following one: https://github.com/FlafyDev/dart-mpris. It appears to address the issue I encountered. I recommend incorporating these changes into your main repository by merging them.

**Comment by provokateurin** [comment]
Can you open a pull request for it? I don't understand why people make the effort to fork a repo and upload a fix but then don't upstream it :woman_shrugging:

**Comment by LucaCoduriV** [comment]
Yep it's weird..
But here is my pull request #5
